server:
  port: 8080
spring:
  datasource:

  # redis 配置
  redis:
    host: 192.168.70.131 # 地址
    port: 6379 # 端口号
    database: 0 #数据库索引
    connect-timeout: 30000ms #连接超时时间
    jedis: #jedis连接池配置
      pool:
        max-active: 8 #最大连接娄
        max-wait: 1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 4 #连接池最大空闲连接
        min-idle: 0 #最小空闲连接
